as-	NIO,NtBO,NBO,NePBO
as	NtE,WE,NePE
as	NI
as:n	NI
as:ár	NI
as:ár	NI
as:ár#vi^đá	NI
as:ár#geah^tes	NI
as:ár#keah^tes	NI
as:á^ris	NI
as:á^rist^tán	NI
as:á^rist^tát	NI
as:á^rist^tá^de	NI
as:á^rist^tá^det	NI
as:á^rist^tá^me	NI
as:á^rist^tá^met	NI
as:á^rist^tis	NI
as:á^rist^tis^ka	NI
as:á^rist^ti^set	NI
as:á^rin	NI
as:á^rii	NI
as:á^riin	NI
as:á^riin^nán	NI
as:á^riin^nát	NI
as:á^riin^ná^de	NI
as:á^riin^ná^det	NI
as:á^riin^ná^me	NI
as:á^riin^ná^met	NI
as:á^riin^nis	NI
as:á^riin^nis^ka	NI
as:á^riin^ni^set	NI
as:á^riid	NI
as:á^riid^dán	NI
as:á^riid^dán^guin	NI
as:á^riid^dát	NI
as:á^riid^dát^guin	NI
as:á^riid^dá^de	NI
as:á^riid^dá^det	NI
as:á^riid^dá^det^guin	NI
as:á^riid^dá^de^guin	NI
as:á^riid^dá^me	NI
as:á^riid^dá^met	NI
as:á^riid^dá^met^guin	NI
as:á^riid^dá^me^guin	NI
as:á^riid^dá^san	NI
as:á^riid^dá^sat	NI
as:á^riid^dá^sis	NI
as:á^riid^dá^sea^set	NI
as:á^riid^dá^sea^me	NI
as:á^riid^dá^sea^met	NI
as:á^riid^dá^seat^te	NI
as:á^riid^dá^seat^tet	NI
as:á^riid^dá^seask^ka	NI
as:á^riid^dis	NI
as:á^riid^dis^ka	NI
as:á^riid^dis^ka^guin	NI
as:á^riid^dis^guin	NI
as:á^riid^di^set	NI
as:á^riid^di^set^guin	NI
as:á^riid^da	NI
as:á^riid	NI
as:á^rii^guin	NI
as:á^ran	NI
as:á^rat	NI
as:á^ra	NI
as:á^ra^san	NI
as:á^ra^sas	NI
as:á^ra^sas^ka	NI
as:á^ra^sat	NI
as:á^ra^sa^de	NI
as:á^ra^sa^det	NI
as:á^ra^sa^me	NI
as:á^ra^sa^met	NI
as:á^ra^sa^set	NI
as:á^rea^set	NI
as:á^rea^me	NI
as:á^rea^met	NI
as:á^reat^te	NI
as:á^reat^tet	NI
as:á^reask^ka	NI
as:t	NI
as:s	NI
as:in	NI
as:i	NI
as:id	NI
as:i^guin	NI
as:i^de	NI
NRK-	NIO,NtBO,NBO,NePBO
NRK	NtE,WE,NePE
NRK	NI
NRK:n	NI
NRK:ár	NI
NRK:ár	NI
NRK:ár#vi^đá	NI
NRK:ár#geah^tes	NI
NRK:ár#keah^tes	NI
NRK:á^ris	NI
NRK:á^rist^tán	NI
NRK:á^rist^tát	NI
NRK:á^rist^tá^de	NI
NRK:á^rist^tá^det	NI
NRK:á^rist^tá^me	NI
NRK:á^rist^tá^met	NI
NRK:á^rist^tis	NI
NRK:á^rist^tis^ka	NI
NRK:á^rist^ti^set	NI
NRK:á^rin	NI
NRK:á^rii	NI
NRK:á^riin	NI
NRK:á^riin^nán	NI
NRK:á^riin^nát	NI
NRK:á^riin^ná^de	NI
NRK:á^riin^ná^det	NI
NRK:á^riin^ná^me	NI
NRK:á^riin^ná^met	NI
NRK:á^riin^nis	NI
NRK:á^riin^nis^ka	NI
NRK:á^riin^ni^set	NI
NRK:á^riid	NI
NRK:á^riid^dán	NI
NRK:á^riid^dán^guin	NI
NRK:á^riid^dát	NI
NRK:á^riid^dát^guin	NI
NRK:á^riid^dá^de	NI
NRK:á^riid^dá^det	NI
NRK:á^riid^dá^det^guin	NI
NRK:á^riid^dá^de^guin	NI
NRK:á^riid^dá^me	NI
NRK:á^riid^dá^met	NI
NRK:á^riid^dá^met^guin	NI
NRK:á^riid^dá^me^guin	NI
NRK:á^riid^dá^san	NI
NRK:á^riid^dá^sat	NI
NRK:á^riid^dá^sis	NI
NRK:á^riid^dá^sea^set	NI
NRK:á^riid^dá^sea^me	NI
NRK:á^riid^dá^sea^met	NI
NRK:á^riid^dá^seat^te	NI
NRK:á^riid^dá^seat^tet	NI
NRK:á^riid^dá^seask^ka	NI
NRK:á^riid^dis	NI
NRK:á^riid^dis^ka	NI
NRK:á^riid^dis^ka^guin	NI
NRK:á^riid^dis^guin	NI
NRK:á^riid^di^set	NI
NRK:á^riid^di^set^guin	NI
NRK:á^riid^da	NI
NRK:á^riid	NI
NRK:á^rii^guin	NI
NRK:á^ran	NI
NRK:á^rat	NI
NRK:á^ra	NI
NRK:á^ra^san	NI
NRK:á^ra^sas	NI
NRK:á^ra^sas^ka	NI
NRK:á^ra^sat	NI
NRK:á^ra^sa^de	NI
NRK:á^ra^sa^det	NI
NRK:á^ra^sa^me	NI
NRK:á^ra^sa^met	NI
NRK:á^ra^sa^set	NI
NRK:á^rea^set	NI
NRK:á^rea^me	NI
NRK:á^rea^met	NI
NRK:á^reat^te	NI
NRK:á^reat^tet	NI
NRK:á^reask^ka	NI
NRK:t	NI
NRK:s	NI
NRK:in	NI
NRK:i	NI
NRK:id	NI
NRK:i^guin	NI
NRK:i^de	NI
CD-	NIO,NtBO,NBO,NePBO
CD	NtE,WE,NePE
CD	NI
CD:n	NI
CD:ár	NI
CD:ár	NI
CD:ár#vi^đá	NI
CD:ár#geah^tes	NI
CD:ár#keah^tes	NI
CD:á^ris	NI
CD:á^rist^tán	NI
CD:á^rist^tát	NI
CD:á^rist^tá^de	NI
CD:á^rist^tá^det	NI
CD:á^rist^tá^me	NI
CD:á^rist^tá^met	NI
CD:á^rist^tis	NI
CD:á^rist^tis^ka	NI
CD:á^rist^ti^set	NI
CD:á^rin	NI
CD:á^rii	NI
CD:á^riin	NI
CD:á^riin^nán	NI
CD:á^riin^nát	NI
CD:á^riin^ná^de	NI
CD:á^riin^ná^det	NI
CD:á^riin^ná^me	NI
CD:á^riin^ná^met	NI
CD:á^riin^nis	NI
CD:á^riin^nis^ka	NI
CD:á^riin^ni^set	NI
CD:á^riid	NI
CD:á^riid^dán	NI
CD:á^riid^dán^guin	NI
CD:á^riid^dát	NI
CD:á^riid^dát^guin	NI
CD:á^riid^dá^de	NI
CD:á^riid^dá^det	NI
CD:á^riid^dá^det^guin	NI
CD:á^riid^dá^de^guin	NI
CD:á^riid^dá^me	NI
CD:á^riid^dá^met	NI
CD:á^riid^dá^met^guin	NI
CD:á^riid^dá^me^guin	NI
CD:á^riid^dá^san	NI
CD:á^riid^dá^sat	NI
CD:á^riid^dá^sis	NI
CD:á^riid^dá^sea^set	NI
CD:á^riid^dá^sea^me	NI
CD:á^riid^dá^sea^met	NI
CD:á^riid^dá^seat^te	NI
CD:á^riid^dá^seat^tet	NI
CD:á^riid^dá^seask^ka	NI
CD:á^riid^dis	NI
CD:á^riid^dis^ka	NI
CD:á^riid^dis^ka^guin	NI
CD:á^riid^dis^guin	NI
CD:á^riid^di^set	NI
CD:á^riid^di^set^guin	NI
CD:á^riid^da	NI
CD:á^riid	NI
CD:á^rii^guin	NI
CD:á^ran	NI
CD:á^rat	NI
CD:á^ra	NI
CD:á^ra^san	NI
CD:á^ra^sas	NI
CD:á^ra^sas^ka	NI
CD:á^ra^sat	NI
CD:á^ra^sa^de	NI
CD:á^ra^sa^det	NI
CD:á^ra^sa^me	NI
CD:á^ra^sa^met	NI
CD:á^ra^sa^set	NI
CD:á^rea^set	NI
CD:á^rea^me	NI
CD:á^rea^met	NI
CD:á^reat^te	NI
CD:á^reat^tet	NI
CD:á^reask^ka	NI
CD:t	NI
CD:s	NI
CD:in	NI
CD:i	NI
CD:id	NI
CD:i^guin	NI
CD:i^de	NI
