#!/bin/bash

cd "$(dirname "$0")"

declare -i fail
for input in *.input; do
    base=${input%%input}
    analyser=${base%%-*}
    hfst-tokenize --gtd -l1 ../tokeniser-"${analyser}"-gt-desc.pmhfst < "${input}" > "${base}"output 2>"${base}"err_output
    if ! diff "${base}"expected "${base}"output; then
        echo "stdout differs for ${base}"
        (( fail++ ))
    fi
done

exit ${fail}
