template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "nort2671"
__REPO__ = "lang-sme"
__UND2C__ = "se"
__UNDEFINED__ = "North Sami"
__UND__ = "sme"
