template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "1c2fffaa917a9c6f340d9887d554609eb561ade6"

[replacements]
__GLOTTOLOG_ID__ = "nort2671"
__REPO__ = "lang-sme"
__UND2C__ = "se"
__UNDEFINED__ = "North Sami"
__UND__ = "sme"
