template = "https://github.com/giellalt/template-lang-und"
rev_id = 324
template_sha = "e348abe50c6a27ca569f7cb967cc9b3a3be7d9f9"

[replacements]
__GLOTTOLOG_ID__ = "nort2671"
__REPO__ = "lang-sme"
__UND2C__ = "se"
__UNDEFINED__ = "North Sami"
__UND__ = "sme"
