[package]
name = "sme"
human_name = "North Sami"
version = "4.2.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sme]
filename = "se-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sme"
platform = "windows"
uuid = "58A8100A-32F2-4006-9DE0-19A418E74B15"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.se"
package = "speller-sme"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sme-mso"
platform = "windows"
uuid = "B6A53E4D-DF01-4E4F-ACFD-8238FD00057F"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sme"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
